export const ORDER_REQUEST = "ORDER_REQUEST";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAIL = "ORDER_FAIL";

export const MY_ORDER_REQUEST = "MY_ORDER_REQUEST";
export const MY_ORDER_SUCCESS = "MY_ORDER_SUCCESS";
export const MY_ORDER_FAIL = "MY_ORDER_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST";
export const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS";
export const ALL_ORDERS_FAIL = "ALL_ORDERS_FAIL";


export const ORDERS_DELETE_REQUEST = "ORDERS_DELETE_REQUEST";
export const ORDERS_DELETE_SUCCESS = "ORDERS_DELETE_SUCCESS";
export const ORDERS_DELETE_FAIL = "ORDERS_DELETE_FAIL";

export const ORDERS_EDIT_REQUEST = "ORDERS_EDIT_REQUEST";
export const ORDERS_EDIT_SUCCESS = "ORDERS_EDIT_SUCCESS";
export const ORDERS_EDIT_FAIL = "ORDERS_EDIT_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";




