export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const PARTICULAR_PRODUCT_REQUEST = "PARTICULAR_PRODUCT_REQUEST";
export const PARTICULAR_PRODUCT_SUCCESS = "PARTICULAR_PRODUCT_SUCCESS";
export const PARTICULAR_PRODUCT_FAIL = "PARTICULAR_PRODUCT_FAIL";


export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";

export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE__SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

export const PRODUCT_EDIT_REQUEST = "PRODUCT_EDIT_REQUEST";
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT__SUCCESS";
export const PRODUCT_EDIT_FAIL = "PRODUCT_EDIT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

