export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_REQUEST = "REGISTER_REQUEST";

export const LOAD_REQUEST = "LOAD_REQUEST";
export const LOAD_SUCCESS = "LOAD_SUCCESS";
export const LOAD_FAIL = "LOAD_FAIL";

export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";


export const CLEAR_ERRORS = "CLEAR_ERRORS";


export const UserUpdate_REQUEST = "UserUpdate_REQUEST";
export const UserUpdate_SUCCESS = "UserUpdate_SUCCESS";
export const UserUpdate_FAIL = "UserUpdate_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";


export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";


export const EMAILRESET_PASSWORD_REQUEST = "EMAILRESET_PASSWORD_REQUEST";
export const EMAILRESET_PASSWORD_SUCCESS = "EMAILRESET_PASSWORD_SUCCESS";
export const EMAILRESET_PASSWORD_FAIL = "EMAILRESET_PASSWORD_FAIL";






